# Generated by Django 4.2.9 on 2026-10-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='版本号')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compat_rules', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '相容性规则版本',
                'verbose_name_plural': '相容性规则版本',
                'db_table': 'wh_compat_rule_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='区域名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='区域说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '保管区',
                'verbose_name_plural': '保管区',
                'db_table': 'wh_storage_zone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='重量上限(kg)')),
                ('max_items', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='件数上限')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zone_rules', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '容量规则版本',
                'verbose_name_plural': '容量规则版本',
                'db_table': 'wh_zone_rule_version',
                'ordering': ['-version'],
                'unique_together': {('zone', 'version')},
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单件重量(kg)'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='入库重量(kg)'),
        ),
        migrations.CreateModel(
            name='ZoneTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移件数')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='转移重量(kg)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='转移时间')),
                ('compat_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse.compatibilityruleversion', verbose_name='相容性规则版本')),
                ('from_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='warehouse.storagezone', verbose_name='转出区域')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_transfers', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse.zoneruleversion', verbose_name='容量规则版本')),
                ('to_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='warehouse.storagezone', verbose_name='转入区域')),
            ],
            options={
                'verbose_name': '区域转移记录',
                'verbose_name_plural': '区域转移记录',
                'db_table': 'wh_zone_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预约件数')),
                ('unit_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预约时单件重量(kg)')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预约重量(kg)')),
                ('status', models.CharField(choices=[('active', '进行中'), ('fulfilled', '已核销'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='失效时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('compat_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='warehouse.compatibilityruleversion', verbose_name='相容性规则版本')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.goods', verbose_name='货物')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='warehouse.zoneruleversion', verbose_name='容量规则版本')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '容量预约',
                'verbose_name_plural': '容量预约',
                'db_table': 'wh_zone_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已用重量(kg)')),
                ('used_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已用件数')),
                ('reserved_weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预约重量(kg)')),
                ('reserved_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预约件数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '区域占用台账',
                'verbose_name_plural': '区域占用台账',
                'db_table': 'wh_zone_occupancy',
            },
        ),
        migrations.CreateModel(
            name='ZoneCategoryOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已用重量(kg)')),
                ('used_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已用件数')),
                ('reserved_weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预约重量(kg)')),
                ('reserved_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预约件数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_occupancies', to='warehouse.category', verbose_name='品类')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_occupancies', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '区域品类占用',
                'verbose_name_plural': '区域品类占用',
                'db_table': 'wh_zone_category_occupancy',
            },
        ),
        migrations.CreateModel(
            name='ZoneCategoryAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_allowances', to='warehouse.category', verbose_name='品类')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='warehouse.zoneruleversion', verbose_name='规则版本')),
            ],
            options={
                'verbose_name': '区域品类准入',
                'verbose_name_plural': '区域品类准入',
                'db_table': 'wh_zone_category_allowance',
            },
        ),
        migrations.CreateModel(
            name='OverLimitApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_weight', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='临时重量额度(kg)')),
                ('extra_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='临时件数额度')),
                ('reason', models.TextField(verbose_name='批准事由')),
                ('expires_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='批准时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_limit_approvals', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_over_limits', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_limit_approvals', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '临时超限批准',
                'verbose_name_plural': '临时超限批准',
                'db_table': 'wh_over_limit_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsZoneStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='存量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_stocks', to='warehouse.goods', verbose_name='货物')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_stocks', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '货物分区存量',
                'verbose_name_plural': '货物分区存量',
                'db_table': 'wh_goods_zone_stock',
            },
        ),
        migrations.CreateModel(
            name='CategoryIncompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_a', to='warehouse.category', verbose_name='品类A')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_b', to='warehouse.category', verbose_name='品类B')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities', to='warehouse.compatibilityruleversion', verbose_name='规则版本')),
            ],
            options={
                'verbose_name': '品类不相容',
                'verbose_name_plural': '品类不相容',
                'db_table': 'wh_category_incompatibility',
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='compat_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='warehouse.compatibilityruleversion', verbose_name='相容性规则版本'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='warehouse.zonereservation', verbose_name='来源预约'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='warehouse.zoneruleversion', verbose_name='容量规则版本'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='warehouse.storagezone', verbose_name='保管区'),
        ),
        migrations.AddConstraint(
            model_name='zoneoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('used_weight__gte', 0)), name='wh_occ_used_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zoneoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('used_items__gte', 0)), name='wh_occ_used_items_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zoneoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('reserved_weight__gte', 0)), name='wh_occ_reserved_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zoneoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('reserved_items__gte', 0)), name='wh_occ_reserved_items_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zonecategoryoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('used_weight__gte', 0)), name='wh_catocc_used_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zonecategoryoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('used_items__gte', 0)), name='wh_catocc_used_items_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zonecategoryoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('reserved_weight__gte', 0)), name='wh_catocc_reserved_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='zonecategoryoccupancy',
            constraint=models.CheckConstraint(check=models.Q(('reserved_items__gte', 0)), name='wh_catocc_reserved_items_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='zonecategoryoccupancy',
            unique_together={('zone', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='zonecategoryallowance',
            unique_together={('rule_version', 'category')},
        ),
        migrations.AddConstraint(
            model_name='goodszonestock',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='wh_gzs_quantity_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='goodszonestock',
            unique_together={('goods', 'zone')},
        ),
        migrations.AddConstraint(
            model_name='categoryincompatibility',
            constraint=models.CheckConstraint(check=models.Q(('category_a__lt', models.F('category_b'))), name='wh_incompat_a_lt_b'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryincompatibility',
            unique_together={('rule_version', 'category_a', 'category_b')},
        ),
    ]
