# Generated by Django 4.2.9 on 2026-10-02 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='临时重量额度(kg)')),
                ('extra_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='临时件数额度')),
                ('reason', models.CharField(max_length=200, verbose_name='批准事由')),
                ('expires_at', models.DateTimeField(verbose_name='失效时间')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overrides', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
            ],
            options={
                'verbose_name': '临时超限批准',
                'verbose_name_plural': '临时超限批准',
                'db_table': 'wh_capacity_override',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区域名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='区域编码')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='区域说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '保管区',
                'verbose_name_plural': '保管区',
                'db_table': 'wh_storage_zone',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ZoneRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='重量上限(kg)')),
                ('max_items', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='件数上限')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('allowed_categories', models.ManyToManyField(blank=True, related_name='zone_rule_versions', to='warehouse.category', verbose_name='准入品类（空为不限制）')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zone_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '区域规则版本',
                'verbose_name_plural': '区域规则版本',
                'db_table': 'wh_zone_rule_version',
                'ordering': ['zone', '-version'],
                'unique_together': {('zone', 'version')},
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单件重量(kg)'),
        ),
        migrations.CreateModel(
            name='ZoneValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('stock_in', '入库'), ('transfer', '转移'), ('reservation', '预约')], max_length=20, verbose_name='操作类型')),
                ('result', models.CharField(choices=[('passed', '通过'), ('rejected', '拒绝')], max_length=20, verbose_name='校验结果')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请重量(kg)')),
                ('limit_weight_snapshot', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='当时重量上限(kg)')),
                ('limit_items_snapshot', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='当时件数上限')),
                ('reasons', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='校验时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_validation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='warehouse.category', verbose_name='品类')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='warehouse.goods', verbose_name='货物')),
                ('override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='warehouse.capacityoverride', verbose_name='依赖的临时超限批准')),
                ('rule_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='warehouse.zoneruleversion', verbose_name='发生时规则版本')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '容量校验记录',
                'verbose_name_plural': '容量校验记录',
                'db_table': 'wh_zone_validation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移数量')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移重量(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='转移时间')),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouse.storagezone', verbose_name='转出保管区')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_transfers', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_transfers', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('rule_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='warehouse.zoneruleversion', verbose_name='目标区校验所用规则版本')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouse.storagezone', verbose_name='转入保管区')),
            ],
            options={
                'verbose_name': '区域转移记录',
                'verbose_name_plural': '区域转移记录',
                'db_table': 'wh_zone_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预约数量')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预约重量(kg)')),
                ('status', models.CharField(choices=[('active', '生效中'), ('fulfilled', '已履约'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='预约失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_reservations', to='warehouse.goods', verbose_name='货物')),
                ('rule_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='warehouse.zoneruleversion', verbose_name='校验所用规则版本')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '容量预约',
                'verbose_name_plural': '容量预约',
                'db_table': 'wh_zone_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前重量(kg)')),
                ('current_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前件数')),
                ('reserved_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预约占用重量(kg)')),
                ('reserved_items', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预约占用件数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '保管区容量',
                'verbose_name_plural': '保管区容量',
                'db_table': 'wh_zone_capacity',
            },
        ),
        migrations.AddField(
            model_name='capacityoverride',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='warehouse.storagezone', verbose_name='保管区'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='warehouse.zoneruleversion', verbose_name='校验所用规则版本'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='warehouse.storagezone', verbose_name='入库保管区'),
        ),
        migrations.CreateModel(
            name='ZoneRuleIncompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibility_as_a', to='warehouse.category', verbose_name='品类甲')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibility_as_b', to='warehouse.category', verbose_name='品类乙')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities', to='warehouse.zoneruleversion', verbose_name='规则版本')),
            ],
            options={
                'verbose_name': '品类相容性规则',
                'verbose_name_plural': '品类相容性规则',
                'db_table': 'wh_zone_rule_incompatibility',
                'unique_together': {('rule_version', 'category_a', 'category_b')},
            },
        ),
        migrations.CreateModel(
            name='StockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='存放数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='warehouse.goods', verbose_name='货物')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='warehouse.storagezone', verbose_name='保管区')),
            ],
            options={
                'verbose_name': '存放明细',
                'verbose_name_plural': '存放明细',
                'db_table': 'wh_stock_placement',
                'unique_together': {('goods', 'zone')},
            },
        ),
    ]
